// Extra definitions for the wrapper

/* masks for types */
#define _DFNT_HDF      0x00000000    /* standard HDF format  */
#define _DFNT_NATIVE   0x00001000    /* native format        */
#define _DFNT_CUSTOM   0x00002000    /* custom format        */
#define _DFNT_LITEND   0x00004000    /* Little Endian format */
#define _DFNT_MASK     0x00000fff    /* format mask */

#define _DFNT_FLOAT32     5
#define _DFNT_FLOAT       5  /* For backward compat; don't use */
#define _DFNT_FLOAT64     6
#define _DFNT_DOUBLE      6  /* For backward compat; don't use */
#define _DFNT_FLOAT128    7  /* No current plans for support */

#define _DFNT_INT8       20
#define _DFNT_UINT8      21

#define _DFNT_INT16      22
#define _DFNT_UINT16     23
#define _DFNT_INT32      24
#define _DFNT_UINT32     25
#define _DFNT_INT64      26
#define _DFNT_UINT64     27
#define _DFNT_INT128     28  /* No current plans for support */
#define _DFNT_UINT128    30  /* No current plans for support */

#define _DFNT_UCHAR8      3  /* 3 chosen for backward compatibility */
#define _DFNT_UCHAR       3  /* uchar=uchar8 for backward combatibility */
#define _DFNT_CHAR8       4  /* 4 chosen for backward compatibility */
#define _DFNT_CHAR        4  /* uchar=uchar8 for backward combatibility */
#define _DFNT_CHAR16     42  /* No current plans for support */
#define _DFNT_UCHAR16    43  /* No current plans for support */

typedef enum {
     DFNT_FLOAT32 = _DFNT_FLOAT32,
     DFNT_FLOAT = _DFNT_FLOAT,  /* For backward compat; don't use */
     DFNT_FLOAT64 = _DFNT_FLOAT64,
     DFNT_DOUBLE = _DFNT_DOUBLE,  /* For backward compat; don't use */
     DFNT_FLOAT128 = _DFNT_FLOAT128,  /* No current plans for support */

     DFNT_INT8 = _DFNT_INT8,
     DFNT_UINT8 = _DFNT_UINT8,

     DFNT_INT16 = _DFNT_INT16,
     DFNT_UINT16 = _DFNT_UINT16,
     DFNT_INT32 = _DFNT_INT32,
     DFNT_UINT32 = _DFNT_UINT32,
     DFNT_INT64 = _DFNT_INT64,
     DFNT_UINT64 = _DFNT_UINT64,
     DFNT_INT128 = _DFNT_INT128,  /* No current plans for support */
     DFNT_UINT128 = _DFNT_UINT128,  /* No current plans for support */

     DFNT_UCHAR8 = _DFNT_UCHAR8,  /* 3 chosen for backward compatibility */
     DFNT_UCHAR = _DFNT_UCHAR,  /* uchar=uchar8 for backward combatibility */
     DFNT_CHAR8 = _DFNT_CHAR8,  /* 4 chosen for backward compatibility */
     DFNT_CHAR = _DFNT_CHAR,  /* uchar=uchar8 for backward combatibility */
     DFNT_CHAR16 = _DFNT_CHAR16,  /* No current plans for support */
     DFNT_UCHAR16 = _DFNT_UCHAR16,  /* No current plans for support */

/* Type info codes for Native Mode datasets */
     DFNT_NFLOAT32 =    (_DFNT_NATIVE | _DFNT_FLOAT32),
     DFNT_NFLOAT64 =    (_DFNT_NATIVE | _DFNT_FLOAT64),
     DFNT_NFLOAT128 =   (_DFNT_NATIVE | _DFNT_FLOAT128),   /* Unsupported */

     DFNT_NINT8 =       (_DFNT_NATIVE | _DFNT_INT8),
     DFNT_NUINT8 =      (_DFNT_NATIVE | _DFNT_UINT8),
     DFNT_NINT16 =      (_DFNT_NATIVE | _DFNT_INT16),
     DFNT_NUINT16 =     (_DFNT_NATIVE | _DFNT_UINT16),
     DFNT_NINT32 =      (_DFNT_NATIVE | _DFNT_INT32),
     DFNT_NUINT32 =     (_DFNT_NATIVE | _DFNT_UINT32),
     DFNT_NINT64 =      (_DFNT_NATIVE | _DFNT_INT64),
     DFNT_NUINT64 =     (_DFNT_NATIVE | _DFNT_UINT64),
     DFNT_NINT128 =     (_DFNT_NATIVE | _DFNT_INT128),     /* Unsupported */
     DFNT_NUINT128 =    (_DFNT_NATIVE | _DFNT_UINT128),    /* Unsupported */

     DFNT_NCHAR8 =      (_DFNT_NATIVE | _DFNT_CHAR8),
     DFNT_NCHAR =       (_DFNT_NATIVE | _DFNT_CHAR8),  /* backward compat */
     DFNT_NUCHAR8 =     (_DFNT_NATIVE | _DFNT_UCHAR8),
     DFNT_NUCHAR =      (_DFNT_NATIVE | _DFNT_UCHAR8),     /* backward compat */
     DFNT_NCHAR16 =     (_DFNT_NATIVE | _DFNT_CHAR16),     /* Unsupported */
     DFNT_NUCHAR16 =    (_DFNT_NATIVE | _DFNT_UCHAR16),    /* Unsupported */

/* Type info codes for Little Endian data */
     DFNT_LFLOAT32 =    (_DFNT_LITEND | _DFNT_FLOAT32),
     DFNT_LFLOAT64 =    (_DFNT_LITEND | _DFNT_FLOAT64),
     DFNT_LFLOAT128 =   (_DFNT_LITEND | _DFNT_FLOAT128),   /* Unsupported */

     DFNT_LINT8 =       (_DFNT_LITEND | _DFNT_INT8),
     DFNT_LUINT8 =      (_DFNT_LITEND | _DFNT_UINT8),
     DFNT_LINT16 =      (_DFNT_LITEND | _DFNT_INT16),
     DFNT_LUINT16 =     (_DFNT_LITEND | _DFNT_UINT16),
     DFNT_LINT32 =      (_DFNT_LITEND | _DFNT_INT32),
     DFNT_LUINT32 =     (_DFNT_LITEND | _DFNT_UINT32),
     DFNT_LINT64 =      (_DFNT_LITEND | _DFNT_INT64),
     DFNT_LUINT64 =     (_DFNT_LITEND | _DFNT_UINT64),
     DFNT_LINT128 =     (_DFNT_LITEND | _DFNT_INT128),     /* Unsupported */
     DFNT_LUINT128 =    (_DFNT_LITEND | _DFNT_UINT128),    /* Unsupported */

     DFNT_LCHAR8 =      (_DFNT_LITEND | _DFNT_CHAR8),
     DFNT_LCHAR =       (_DFNT_LITEND | _DFNT_CHAR8),  /* backward compat */
     DFNT_LUCHAR8 =     (_DFNT_LITEND | _DFNT_UCHAR8),
     DFNT_LUCHAR =      (_DFNT_LITEND | _DFNT_UCHAR8),     /* backward compat */
     DFNT_LCHAR16 =     (_DFNT_LITEND | _DFNT_CHAR16),     /* Unsupported */
     DFNT_LUCHAR16 =    (_DFNT_LITEND | _DFNT_UCHAR16),    /* Unsupported */
} hdf_data_type;
